.TH "FileManager.FilesPanel" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.FilesPanel \- Класс файловой панели  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFilesPanel\fP (bool isLeftPanel)"
.br
.RI "Конструктор класса "
.ti -1c
.RI "void \fBAddBufferSelectedPositionCursor\fP (int item)"
.br
.RI "Добавление и удаление позиции курсора в буфер для осуществления общего действия с группой "
.ti -1c
.RI "void \fBUpdatePath\fP (string path)"
.br
.RI "Одновление данных при изменении текущей директории "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsLeftPanel\fP\fC [get, set]\fP"
.br
.RI "Является панел левой "
.ti -1c
.RI "string \fBCurrentPath\fP\fC [get, set]\fP"
.br
.RI "Путь к теущей директории "
.ti -1c
.RI "List< \fBAttributes\fP > \fBCurrentListDirAndFiles\fP\fC [get, set]\fP"
.br
.RI "Список файлов и директорий в текущей директории "
.ti -1c
.RI "int \fBFirstLineWhenScrolling\fP\fC [get, set]\fP"
.br
.RI "Первая отображаемая линия при скроллинге "
.ti -1c
.RI "int \fBAbsoluteCursorPosition\fP\fC [get, set]\fP"
.br
.RI "Абсолютная позиция курсора "
.ti -1c
.RI "int \fBRelativeCursorPosition\fP\fC [get, set]\fP"
.br
.RI "Позиция курсора относительно окна панели при скроллинге "
.ti -1c
.RI "HashSet< int > \fBBufferSelectedPositionCursor\fP\fC [get, set]\fP"
.br
.RI "Список выделенных абсолютных позиций курсора "
.in -1c
.SH "Detailed Description"
.PP 
Класс файловой панели 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FileManager\&.FilesPanel\&.FilesPanel (bool isLeftPanel)"

.PP
Конструктор класса 
.PP
\fBParameters\fP
.RS 4
\fIisLeftPanel\fP Является ли создаваемая панель левой
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void FileManager\&.FilesPanel\&.AddBufferSelectedPositionCursor (int item)"

.PP
Добавление и удаление позиции курсора в буфер для осуществления общего действия с группой 
.PP
\fBParameters\fP
.RS 4
\fIitem\fP 
.RE
.PP

.SS "void FileManager\&.FilesPanel\&.UpdatePath (string path)"

.PP
Одновление данных при изменении текущей директории 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "int FileManager\&.FilesPanel\&.AbsoluteCursorPosition\fC [get]\fP, \fC [set]\fP"

.PP
Абсолютная позиция курсора 
.SS "HashSet<int> FileManager\&.FilesPanel\&.BufferSelectedPositionCursor\fC [get]\fP, \fC [set]\fP"

.PP
Список выделенных абсолютных позиций курсора 
.SS "List<\fBAttributes\fP> FileManager\&.FilesPanel\&.CurrentListDirAndFiles\fC [get]\fP, \fC [set]\fP"

.PP
Список файлов и директорий в текущей директории 
.SS "string FileManager\&.FilesPanel\&.CurrentPath\fC [get]\fP, \fC [set]\fP"

.PP
Путь к теущей директории 
.SS "int FileManager\&.FilesPanel\&.FirstLineWhenScrolling\fC [get]\fP, \fC [set]\fP"

.PP
Первая отображаемая линия при скроллинге 
.SS "bool FileManager\&.FilesPanel\&.IsLeftPanel\fC [get]\fP, \fC [set]\fP"

.PP
Является панел левой 
.SS "int FileManager\&.FilesPanel\&.RelativeCursorPosition\fC [get]\fP, \fC [set]\fP"

.PP
Позиция курсора относительно окна панели при скроллинге 

.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
