.TH "FileManager.ErrorLog" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.ErrorLog \- Класс для записи логов об ошибках в файл  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBErrorLog\fP (object ob, string message, string trace)"
.br
.RI "Получение информации об ошибке и запись ее в файл "
.in -1c
.SH "Detailed Description"
.PP 
Класс для записи логов об ошибках в файл 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FileManager\&.ErrorLog\&.ErrorLog (object ob, string message, string trace)"

.PP
Получение информации об ошибке и запись ее в файл 
.PP
\fBParameters\fP
.RS 4
\fIob\fP Класс в котором произошла ошибка
.br
\fImessage\fP Сгенерированное сообщение
.br
\fItrace\fP Файл и строка с ошибкой
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
