.TH "FileManager.CL_AddChar" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.CL_AddChar \- Класс обрабатывающий все нажатия клавиш, кроме указанных выше в методе Management() класса \fBCommandLine\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileManager\&.ICommand< ConsoleKeyInfo >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCanExecute\fP (ConsoleKeyInfo click)"
.br
.RI "Присвоение полю Click кода нажатой клавиши "
.ti -1c
.RI "bool \fBExecute\fP ()"
.br
.RI "Добавление символа нажатой клавиши в командной строке "
.in -1c
.SH "Detailed Description"
.PP 
Класс обрабатывающий все нажатия клавиш, кроме указанных выше в методе Management() класса \fBCommandLine\fP 


.SH "Member Function Documentation"
.PP 
.SS "bool FileManager\&.CL_AddChar\&.CanExecute (ConsoleKeyInfo click)"

.PP
Присвоение полю Click кода нажатой клавиши 
.PP
\fBParameters\fP
.RS 4
\fIclick\fP 
.RE
.PP
\fBReturns\fP
.RS 4
true or false
.RE
.PP

.SS "bool FileManager\&.CL_AddChar\&.Execute ()"

.PP
Добавление символа нажатой клавиши в командной строке 

.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
