.TH "FileManager.CreateDirectory" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.CreateDirectory \- Класс для создания директории  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileManager\&.ICommand< ConsoleKeyInfo >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCanExecute\fP (ConsoleKeyInfo click)"
.br
.RI "Проверка условия для выполнения метода Execute "
.ti -1c
.RI "bool \fBExecute\fP ()"
.br
.RI "Создание новой директории при помощи метода Create и обновление окна приложения после создания "
.ti -1c
.RI "string \fBGetUserNameDirectory\fP ()"
.br
.RI "Получение от пользователя имени новой директории "
.in -1c
.SH "Detailed Description"
.PP 
Класс для создания директории 


.SH "Member Function Documentation"
.PP 
.SS "bool FileManager\&.CreateDirectory\&.CanExecute (ConsoleKeyInfo click)"

.PP
Проверка условия для выполнения метода Execute 
.PP
\fBParameters\fP
.RS 4
\fIclick\fP Информация о нажатой клавише
.RE
.PP
\fBReturns\fP
.RS 4
true or false
.RE
.PP

.SS "bool FileManager\&.CreateDirectory\&.Execute ()"

.PP
Создание новой директории при помощи метода Create и обновление окна приложения после создания 
.PP
\fBReturns\fP
.RS 4
Выход из программы
.RE
.PP

.SS "string FileManager\&.CreateDirectory\&.GetUserNameDirectory ()"

.PP
Получение от пользователя имени новой директории 
.PP
\fBReturns\fP
.RS 4
Имя директории
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
