.TH "FileManager" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAttributes\fP"
.br
.RI "Тип данных для хранения информации об обьектах файловой системы "
.ti -1c
.RI "class \fBChangeActivePanel\fP"
.br
.RI "Класс, осуществляющий выбор активной файловой панели\&. Реализует паттерн Command "
.ti -1c
.RI "class \fBCL_AddChar\fP"
.br
.RI "Класс обрабатывающий все нажатия клавиш, кроме указанных выше в методе Management() класса \fBCommandLine\fP "
.ti -1c
.RI "class \fBCL_AddPath\fP"
.br
.RI "Класс, добавляющий текщий путь в командную строку "
.ti -1c
.RI "class \fBCL_Backspace\fP"
.br
.RI "Класс, удаляющий символ до курсора "
.ti -1c
.RI "class \fBCL_CD\fP"
.br
.RI "Класс для перехода в указанную директорию "
.ti -1c
.RI "class \fBCL_Copy\fP"
.br
.RI "Класс для копирования файла и директории "
.ti -1c
.RI "class \fBCL_Delete\fP"
.br
.RI "Класс для удаления обьекта файловой системы "
.ti -1c
.RI "class \fBCL_DownArrow\fP"
.br
.RI "Класс перебора комманд LIFO и добавления их в командную строку "
.ti -1c
.RI "class \fBCL_Enter\fP"
.br
.RI "Класс, обрабатывающий командную строку после ввода "
.ti -1c
.RI "class \fBCL_Escape\fP"
.br
.RI "Выход из режима командной строки "
.ti -1c
.RI "class \fBCL_LeftArrow\fP"
.br
.RI "Класс, перемещающий курсор влево "
.ti -1c
.RI "class \fBCL_Rename\fP"
.br
.RI "Класс переименования обьекта файловой системы "
.ti -1c
.RI "class \fBCL_RightArrow\fP"
.br
.RI "Класс, перемещающий курсор вправо "
.ti -1c
.RI "class \fBCL_UpArrow\fP"
.br
.RI "Класс перебора комманд FIFO в буфере и добавления их в командную строку "
.ti -1c
.RI "class \fBClear\fP"
.br
.RI "Класс для отрисовки рамок и пустых форм "
.ti -1c
.RI "class \fBColorTextAndBackground\fP"
.br
.RI "Цветовые схемы "
.ti -1c
.RI "class \fBCommandLine\fP"
.br
.RI "Класс реализующий командную строку "
.ti -1c
.RI "class \fBCopy\fP"
.br
.RI "Подготовка к копированию обьектов "
.ti -1c
.RI "class \fBCreateDirectory\fP"
.br
.RI "Класс для создания директории "
.ti -1c
.RI "class \fBCreateFile\fP"
.br
.RI "Класс для создания файла "
.ti -1c
.RI "class \fBCustomFileCopy\fP"
.br
.RI "Класс для копирования файла с возможностью отслеживания промежуточных сосотояний и завершения процесса через события "
.ti -1c
.RI "class \fBCustomMethods\fP"
.br
.RI "Класс кастомных методов "
.ti -1c
.RI "class \fBDelete\fP"
.br
.RI "Класс для удаления файлов или директорий "
.ti -1c
.RI "class \fBDesktop\fP"
.br
.RI "Класс отвечающий за создание главного окна приложения "
.ti -1c
.RI "class \fBDownArrow\fP"
.br
.RI "Класс для перемещения курсора на одну позицию вниз "
.ti -1c
.RI "class \fBEditFile\fP"
.br
.RI "Класс для открытия файла в блокноте "
.ti -1c
.RI "class \fBErrorLog\fP"
.br
.RI "Класс для записи логов об ошибках в файл "
.ti -1c
.RI "class \fBFilesPanel\fP"
.br
.RI "Класс файловой панели "
.ti -1c
.RI "class \fBHelp\fP"
.br
.RI "Класс для вывода справки по приложению на экран "
.ti -1c
.RI "interface \fBICommand\fP"
.br
.RI "Интерфейс для реализации паттерна Command "
.ti -1c
.RI "class \fBKeyEnter\fP"
.br
.RI "Класс для осуществления действий, при нажатии на клавишу Enter "
.ti -1c
.RI "class \fBMove\fP"
.br
.RI "Класс переноса файла или директории "
.ti -1c
.RI "class \fBProgram\fP"
.br
.RI "Главный метод приложения "
.ti -1c
.RI "class \fBQuit\fP"
.br
.RI "Класс выхода из приложения с сохранением текущийх настроек пользователя 
.br
 "
.ti -1c
.RI "class \fBRenameObject\fP"
.br
.RI "Класс переименования обьекта "
.ti -1c
.RI "class \fBRequestToDisk\fP"
.br
.RI "Класс для получения информации с диска "
.ti -1c
.RI "class \fBSelectCommandLine\fP"
.br
.RI "Класс выбора коммандной строки "
.ti -1c
.RI "class \fBSelectDisk\fP"
.br
.RI "Класс выбора диска "
.ti -1c
.RI "class \fBSelectObject\fP"
.br
.RI "Класс выбора обьекта "
.ti -1c
.RI "class \fBThreadControlSizeWindow\fP"
.br
.RI "Класс для отслеживания изменения размера окна приложения "
.ti -1c
.RI "class \fBTree\fP"
.br
.RI "Класс построения дерева файлов и дирректорий "
.ti -1c
.RI "class \fBUpArrow\fP"
.br
.RI "Класс для перемещения курсора на одну позицию вверх "
.ti -1c
.RI "class \fBUserData\fP"
.br
.RI "Класс с данными о приложении, которые сохраняются на диске "
.ti -1c
.RI "class \fBView\fP"
.br
.RI "Класс для вывода информации на экран "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate void \fBProgressChangeDelegate\fP (double Persentage, ref bool Cancel)"
.br
.RI "Тип делегата для события OnProgressChanged "
.ti -1c
.RI "delegate void \fBCompletedelegate\fP ()"
.br
.RI "Тип делегата для события OnComplete "
.ti -1c
.RI "delegate void \fBResizeWindow\fP ()"
.br
.RI "Тип делегата для события Resize "
.in -1c
.SH "Function Documentation"
.PP 
.SS "delegate void FileManager\&.Completedelegate ()"

.PP
Тип делегата для события OnComplete 
.SS "delegate void FileManager\&.ProgressChangeDelegate (double Persentage, ref bool Cancel)"

.PP
Тип делегата для события OnProgressChanged 
.PP
\fBParameters\fP
.RS 4
\fIPersentage\fP Проценты
.br
\fICancel\fP Закрытие потока
.RE
.PP

.SS "delegate void FileManager\&.ResizeWindow ()"

.PP
Тип делегата для события Resize 
.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
