.TH "FileManager.Program" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.Program \- Главный метод приложения  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.RI "Точка входа в программу "
.ti -1c
.RI "static void \fBControlSize\fP ()"
.br
.RI "Метод, вызываемый при изменении размеров окна приложения "
.in -1c
.SH "Detailed Description"
.PP 
Главный метод приложения 


.SH "Member Function Documentation"
.PP 
.SS "static void FileManager\&.Program\&.ControlSize ()\fC [static]\fP"

.PP
Метод, вызываемый при изменении размеров окна приложения 
.SS "static void FileManager\&.Program\&.Main ()\fC [static]\fP"

.PP
Точка входа в программу 

.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
