.TH "FileManager.CL_RightArrow" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.CL_RightArrow \- Класс, перемещающий курсор вправо  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileManager\&.ICommand< ConsoleKeyInfo >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCanExecute\fP (ConsoleKeyInfo click)"
.br
.RI "Проверка нажатия горячей клавиши "
.ti -1c
.RI "bool \fBExecute\fP ()"
.br
.RI "Перемещение курсора вправо "
.in -1c
.SH "Detailed Description"
.PP 
Класс, перемещающий курсор вправо 


.SH "Member Function Documentation"
.PP 
.SS "bool FileManager\&.CL_RightArrow\&.CanExecute (ConsoleKeyInfo click)"

.PP
Проверка нажатия горячей клавиши 
.PP
\fBParameters\fP
.RS 4
\fIclick\fP Код горячей клавиши
.RE
.PP
\fBReturns\fP
.RS 4
true or false
.RE
.PP

.SS "bool FileManager\&.CL_RightArrow\&.Execute ()"

.PP
Перемещение курсора вправо 

.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
