.TH "FileManager.CL_CD" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.CL_CD \- Класс для перехода в указанную директорию  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileManager\&.ICommand< string >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCanExecute\fP (string value)"
.br
.RI "Сравнение входящей строки с контрольной строкой "
.ti -1c
.RI "bool \fBExecute\fP ()"
.br
.RI "Переход в указанную директорию "
.in -1c
.SH "Detailed Description"
.PP 
Класс для перехода в указанную директорию 


.SH "Member Function Documentation"
.PP 
.SS "bool FileManager\&.CL_CD\&.CanExecute (string value)"

.PP
Сравнение входящей строки с контрольной строкой 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Код горячей клавиши
.RE
.PP
\fBReturns\fP
.RS 4
true or false
.RE
.PP

.SS "bool FileManager\&.CL_CD\&.Execute ()"

.PP
Переход в указанную директорию 

.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
