.TH "FileManager.CL_Escape" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.CL_Escape \- Выход из режима командной строки  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileManager\&.ICommand< ConsoleKeyInfo >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCanExecute\fP (ConsoleKeyInfo click)"
.br
.RI "Проверка нажатия горячей клавиши "
.ti -1c
.RI "bool \fBExecute\fP ()"
.br
.RI "Выход из режима командной строки "
.in -1c
.SH "Detailed Description"
.PP 
Выход из режима командной строки 


.SH "Member Function Documentation"
.PP 
.SS "bool FileManager\&.CL_Escape\&.CanExecute (ConsoleKeyInfo click)"

.PP
Проверка нажатия горячей клавиши 
.PP
\fBParameters\fP
.RS 4
\fIclick\fP Код горячей клавиши
.RE
.PP
\fBReturns\fP
.RS 4
true or false
.RE
.PP

.SS "bool FileManager\&.CL_Escape\&.Execute ()"

.PP
Выход из режима командной строки 

.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
