.TH "FileManager.ChangeActivePanel" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.ChangeActivePanel \- Класс, осуществляющий выбор активной файловой панели\&. Реализует паттерн Command  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileManager\&.ICommand< ConsoleKeyInfo >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCanExecute\fP (ConsoleKeyInfo click)"
.br
.RI "Проверка условия для выполнения метода Execute "
.ti -1c
.RI "bool \fBExecute\fP ()"
.br
.RI "Переключение активной файловой панели "
.in -1c
.SH "Detailed Description"
.PP 
Класс, осуществляющий выбор активной файловой панели\&. Реализует паттерн Command 


.SH "Member Function Documentation"
.PP 
.SS "bool FileManager\&.ChangeActivePanel\&.CanExecute (ConsoleKeyInfo click)"

.PP
Проверка условия для выполнения метода Execute 
.PP
\fBParameters\fP
.RS 4
\fIclick\fP Информация о нажатой клавише
.RE
.PP
\fBReturns\fP
.RS 4
true or false
.RE
.PP

.SS "bool FileManager\&.ChangeActivePanel\&.Execute ()"

.PP
Переключение активной файловой панели 
.PP
\fBReturns\fP
.RS 4
Выход из программы
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
