.TH "FileManager.Clear" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.Clear \- Класс для отрисовки рамок и пустых форм  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClear\fP ()"
.br
.RI "Конструктор класса "
.ti -1c
.RI "void \fBFPanel\fP (\fBFilesPanel\fP panel)"
.br
.RI "Отрисовка рамок одной файловой панели "
.ti -1c
.RI "void \fBMessage\fP ()"
.br
.RI "Отрисовка пустой формы для сообщений "
.ti -1c
.RI "void \fBHelp\fP ()"
.br
.RI "Отрисовка рамок окна \fBHelp\fP "
.ti -1c
.RI "void \fBCopy\fP ()"
.br
.RI "Отрисовка рамок окна \fBCopy\fP "
.ti -1c
.RI "void \fBCommandLine\fP ()"
.br
.RI "Отрисовка рамок командной строки "
.ti -1c
.RI "int \fBMarginLeft\fP (\fBFilesPanel\fP panel)"
.br
.RI "Вычисление отступа слева "
.in -1c
.SH "Detailed Description"
.PP 
Класс для отрисовки рамок и пустых форм 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FileManager\&.Clear\&.Clear ()"

.PP
Конструктор класса 
.SH "Member Function Documentation"
.PP 
.SS "void FileManager\&.Clear\&.CommandLine ()"

.PP
Отрисовка рамок командной строки 
.SS "void FileManager\&.Clear\&.Copy ()"

.PP
Отрисовка рамок окна \fBCopy\fP 
.SS "void FileManager\&.Clear\&.FPanel (\fBFilesPanel\fP panel)"

.PP
Отрисовка рамок одной файловой панели 
.PP
\fBParameters\fP
.RS 4
\fIpanel\fP 
.RE
.PP

.SS "void FileManager\&.Clear\&.Help ()"

.PP
Отрисовка рамок окна \fBHelp\fP 
.SS "int FileManager\&.Clear\&.MarginLeft (\fBFilesPanel\fP panel)"

.PP
Вычисление отступа слева 
.PP
\fBParameters\fP
.RS 4
\fIpanel\fP Текущая панель
.RE
.PP
\fBReturns\fP
.RS 4
Количество сомволов
.RE
.PP

.SS "void FileManager\&.Clear\&.Message ()"

.PP
Отрисовка пустой формы для сообщений 

.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
