.TH "FileManager.CL_Delete" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.CL_Delete \- Класс для удаления обьекта файловой системы  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileManager\&.ICommand< string >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCanExecute\fP (string value)"
.br
.RI "Сравнение входящей строки с контрольной строкой "
.ti -1c
.RI "bool \fBExecute\fP ()"
.br
.RI "Удаление директории или файла "
.ti -1c
.RI "bool \fBConfirmation\fP (string path)"
.br
.RI "Подтверждение пользователем удаления "
.in -1c
.SH "Detailed Description"
.PP 
Класс для удаления обьекта файловой системы 


.SH "Member Function Documentation"
.PP 
.SS "bool FileManager\&.CL_Delete\&.CanExecute (string value)"

.PP
Сравнение входящей строки с контрольной строкой 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Входящая строка
.RE
.PP
\fBReturns\fP
.RS 4
true or false
.RE
.PP

.SS "bool FileManager\&.CL_Delete\&.Confirmation (string path)"

.PP
Подтверждение пользователем удаления 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP Путь к удалямому обьекту
.RE
.PP
\fBReturns\fP
.RS 4
true or false
.RE
.PP

.SS "bool FileManager\&.CL_Delete\&.Execute ()"

.PP
Удаление директории или файла 
.PP
\fBReturns\fP
.RS 4

.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
