.TH "FileManager.UserData" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.UserData \- Класс с данными о приложении, которые сохраняются на диске  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSerialize\fP ()"
.br
.RI "Серилизация данных в формат json "
.ti -1c
.RI "void \fBDeserialize\fP ()"
.br
.RI "Десирилизация данных из json "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBUserData\fP \fBGetInstance\fP ()"
.br
.RI "Реализация паттерна singlton "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBLeftPanel_CurrentPath\fP\fC [get, set]\fP"
.br
.RI "Текущий путь для левой панели "
.ti -1c
.RI "int \fBLeftPanel_FirstLineWhenScrolling\fP\fC [get, set]\fP"
.br
.RI "Первая отображаемая строка при скролинге для левой панели "
.ti -1c
.RI "int \fBLeftPanel_AbsoluteCursorPosition\fP\fC [get, set]\fP"
.br
.RI "Абсолютная позиция курсора для левой панели "
.ti -1c
.RI "int \fBLeftPanel_RelativeCursorPosition\fP\fC [get, set]\fP"
.br
.RI "Позиция курсора относительно окна для левой панели "
.ti -1c
.RI "string \fBRightPanel_CurrentPath\fP\fC [get, set]\fP"
.br
.RI "Текущий путь для правой панели "
.ti -1c
.RI "int \fBRightPanel_FirstLineWhenScrolling\fP\fC [get, set]\fP"
.br
.RI "Первая отображаемая строка при скролинге для левой панели "
.ti -1c
.RI "int \fBRightPanel_AbsoluteCursorPosition\fP\fC [get, set]\fP"
.br
.RI "Абсолютная позиция курсора для левой панели "
.ti -1c
.RI "int \fBRightPanel_RelativeCursorPosition\fP\fC [get, set]\fP"
.br
.RI "Позиция курсора относительно окна для левой панели "
.ti -1c
.RI "bool \fBActivePanel_IsLeftPanel\fP\fC [get, set]\fP"
.br
.RI "Является ли активная панель левой "
.ti -1c
.RI "int \fBWindowWidth\fP\fC [get, set]\fP"
.br
.RI "Ширина окна приложения "
.ti -1c
.RI "int \fBWindowHeight\fP\fC [get, set]\fP"
.br
.RI "Высота окна приложения "
.in -1c
.SH "Detailed Description"
.PP 
Класс с данными о приложении, которые сохраняются на диске 


.SH "Member Function Documentation"
.PP 
.SS "void FileManager\&.UserData\&.Deserialize ()"

.PP
Десирилизация данных из json 
.SS "static \fBUserData\fP FileManager\&.UserData\&.GetInstance ()\fC [static]\fP"

.PP
Реализация паттерна singlton 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "void FileManager\&.UserData\&.Serialize ()"

.PP
Серилизация данных в формат json 
.SH "Property Documentation"
.PP 
.SS "bool FileManager\&.UserData\&.ActivePanel_IsLeftPanel\fC [get]\fP, \fC [set]\fP"

.PP
Является ли активная панель левой 
.SS "int FileManager\&.UserData\&.LeftPanel_AbsoluteCursorPosition\fC [get]\fP, \fC [set]\fP"

.PP
Абсолютная позиция курсора для левой панели 
.SS "string FileManager\&.UserData\&.LeftPanel_CurrentPath\fC [get]\fP, \fC [set]\fP"

.PP
Текущий путь для левой панели 
.SS "int FileManager\&.UserData\&.LeftPanel_FirstLineWhenScrolling\fC [get]\fP, \fC [set]\fP"

.PP
Первая отображаемая строка при скролинге для левой панели 
.SS "int FileManager\&.UserData\&.LeftPanel_RelativeCursorPosition\fC [get]\fP, \fC [set]\fP"

.PP
Позиция курсора относительно окна для левой панели 
.SS "int FileManager\&.UserData\&.RightPanel_AbsoluteCursorPosition\fC [get]\fP, \fC [set]\fP"

.PP
Абсолютная позиция курсора для левой панели 
.SS "string FileManager\&.UserData\&.RightPanel_CurrentPath\fC [get]\fP, \fC [set]\fP"

.PP
Текущий путь для правой панели 
.SS "int FileManager\&.UserData\&.RightPanel_FirstLineWhenScrolling\fC [get]\fP, \fC [set]\fP"

.PP
Первая отображаемая строка при скролинге для левой панели 
.SS "int FileManager\&.UserData\&.RightPanel_RelativeCursorPosition\fC [get]\fP, \fC [set]\fP"

.PP
Позиция курсора относительно окна для левой панели 
.SS "int FileManager\&.UserData\&.WindowHeight\fC [get]\fP, \fC [set]\fP"

.PP
Высота окна приложения 
.SS "int FileManager\&.UserData\&.WindowWidth\fC [get]\fP, \fC [set]\fP"

.PP
Ширина окна приложения 

.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
