.TH "FileManager.UpArrow" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.UpArrow \- Класс для перемещения курсора на одну позицию вверх  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileManager\&.ICommand< ConsoleKeyInfo >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCanExecute\fP (ConsoleKeyInfo click)"
.br
.RI "Проверка условия для выполнения метода Execute "
.ti -1c
.RI "bool \fBExecute\fP ()"
.br
.RI "Перемещение курсора на одну позицию вверх "
.in -1c
.SH "Detailed Description"
.PP 
Класс для перемещения курсора на одну позицию вверх 


.SH "Member Function Documentation"
.PP 
.SS "bool FileManager\&.UpArrow\&.CanExecute (ConsoleKeyInfo click)"

.PP
Проверка условия для выполнения метода Execute 
.PP
\fBParameters\fP
.RS 4
\fIclick\fP Информация о нажатой клавише
.RE
.PP
\fBReturns\fP
.RS 4
true or false
.RE
.PP

.SS "bool FileManager\&.UpArrow\&.Execute ()"

.PP
Перемещение курсора на одну позицию вверх 
.PP
\fBReturns\fP
.RS 4
true or false
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
