.TH "FileManager.CL_AddPath" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.CL_AddPath \- Класс, добавляющий текщий путь в командную строку  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileManager\&.ICommand< ConsoleKeyInfo >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCanExecute\fP (ConsoleKeyInfo click)"
.br
.RI "Проверка нажатия горячей клавиши "
.ti -1c
.RI "bool \fBExecute\fP ()"
.br
.RI "Добавление текщего пути в командную строку "
.in -1c
.SH "Detailed Description"
.PP 
Класс, добавляющий текщий путь в командную строку 


.SH "Member Function Documentation"
.PP 
.SS "bool FileManager\&.CL_AddPath\&.CanExecute (ConsoleKeyInfo click)"

.PP
Проверка нажатия горячей клавиши 
.PP
\fBParameters\fP
.RS 4
\fIclick\fP Код горячей клавиши
.RE
.PP
\fBReturns\fP
.RS 4
true or false
.RE
.PP

.SS "bool FileManager\&.CL_AddPath\&.Execute ()"

.PP
Добавление текщего пути в командную строку 

.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
