.TH "FileManager.Copy" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.Copy \- Подготовка к копированию обьектов  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileManager\&.ICommand< ConsoleKeyInfo >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCopy\fP (\fBFilesPanel\fP activePanel)"
.br
.RI "Конструктор класса "
.ti -1c
.RI "\fBCopy\fP ()"
.br
.RI "Конструктор класса "
.ti -1c
.RI "bool \fBCanExecute\fP (ConsoleKeyInfo click)"
.br
.RI "Проверка условия для выполнения метода Execute "
.ti -1c
.RI "bool \fBExecute\fP ()"
.br
.RI "Запуск цепи проверок для копирования и обновление окна программы после копирования "
.ti -1c
.RI "void \fBCheckBufferSelected\fP ()"
.br
.RI "Проверяется наличие выделенных обьектов и если такие есть, то они поочередно отправляются на проверку\&. Если выделенных обьектов нет, то на проверку отправляется обьект, на котором находится курсор\&. "
.ti -1c
.RI "void \fBSelectTargetPanel\fP ()"
.br
.RI "Вычисление пути назначения "
.ti -1c
.RI "void \fBCheck\fP ()"
.br
.RI "Проверка равентства текущего пути и пути назначения "
.ti -1c
.RI "void \fBCheckingCorrectnessCurrentPath\fP ()"
.br
.RI "Проверка корректности текущего пути "
.ti -1c
.RI "void \fBCheckingExistenceObjectInDestinationFolder\fP (\fBAttributes\fP attributes)"
.br
.RI "Проверка существования текущего обьекта в папке назначения "
.ti -1c
.RI "void \fBCheckFreeSpaceFile\fP (\fBAttributes\fP attributes)"
.br
.RI "Проверка достаточности свободного места для файла на диске - получателе "
.ti -1c
.RI "void \fBCheckFreeSpaceDirectory\fP (\fBAttributes\fP attributes)"
.br
.RI "Проверка достаточности свободного места для директории на диске - получателе "
.ti -1c
.RI "void \fBCopyFile\fP (string path)"
.br
.RI "Создание экземпляра класса для копирования файла, добавление к событию метода, получающего проценты выполнения и запуск потоков для копирования "
.ti -1c
.RI "void \fBCopyDirectory\fP (string path, List< \fBAttributes\fP > newTreeFiles)"
.br
.RI "Копирование директории "
.ti -1c
.RI "void \fBViewPersentageToConsole\fP (double persentage, ref bool cancelFlag)"
.br
.RI "Получение процентов и завершение процесса копирования "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBFilesPanel\fP \fBActivePanel\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBFilesPanel\fP \fBTargetPanel\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Подготовка к копированию обьектов 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FileManager\&.Copy\&.Copy (\fBFilesPanel\fP activePanel)"

.PP
Конструктор класса 
.PP
\fBParameters\fP
.RS 4
\fIactivePanel\fP Активная панель
.RE
.PP

.SS "FileManager\&.Copy\&.Copy ()"

.PP
Конструктор класса 
.SH "Member Function Documentation"
.PP 
.SS "bool FileManager\&.Copy\&.CanExecute (ConsoleKeyInfo click)"

.PP
Проверка условия для выполнения метода Execute 
.PP
\fBParameters\fP
.RS 4
\fIclick\fP Информация о нажатой клавише
.RE
.PP
\fBReturns\fP
.RS 4
true or false
.RE
.PP

.SS "void FileManager\&.Copy\&.Check ()"

.PP
Проверка равентства текущего пути и пути назначения 
.SS "void FileManager\&.Copy\&.CheckBufferSelected ()"

.PP
Проверяется наличие выделенных обьектов и если такие есть, то они поочередно отправляются на проверку\&. Если выделенных обьектов нет, то на проверку отправляется обьект, на котором находится курсор\&. 
.SS "void FileManager\&.Copy\&.CheckFreeSpaceDirectory (\fBAttributes\fP attributes)"

.PP
Проверка достаточности свободного места для директории на диске - получателе 
.PP
\fBParameters\fP
.RS 4
\fIattributes\fP Атрибуты копируемой директории
.RE
.PP

.SS "void FileManager\&.Copy\&.CheckFreeSpaceFile (\fBAttributes\fP attributes)"

.PP
Проверка достаточности свободного места для файла на диске - получателе 
.PP
\fBParameters\fP
.RS 4
\fIattributes\fP Атрибуты копируемого файла
.RE
.PP

.SS "void FileManager\&.Copy\&.CheckingCorrectnessCurrentPath ()"

.PP
Проверка корректности текущего пути 
.SS "void FileManager\&.Copy\&.CheckingExistenceObjectInDestinationFolder (\fBAttributes\fP attributes)"

.PP
Проверка существования текущего обьекта в папке назначения 
.PP
\fBParameters\fP
.RS 4
\fIattributes\fP Атрибуты обьекта копирования
.RE
.PP

.SS "void FileManager\&.Copy\&.CopyDirectory (string path, List< \fBAttributes\fP > newTreeFiles)"

.PP
Копирование директории 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP Путь к директории
.br
\fInewTreeFiles\fP Внутреннее дерево файлов и директорий
.RE
.PP

.SS "void FileManager\&.Copy\&.CopyFile (string path)"

.PP
Создание экземпляра класса для копирования файла, добавление к событию метода, получающего проценты выполнения и запуск потоков для копирования 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP Путь к текущему
.RE
.PP

.SS "bool FileManager\&.Copy\&.Execute ()"

.PP
Запуск цепи проверок для копирования и обновление окна программы после копирования 
.PP
\fBReturns\fP
.RS 4
Выход из программы
.RE
.PP

.SS "void FileManager\&.Copy\&.SelectTargetPanel ()"

.PP
Вычисление пути назначения 
.SS "void FileManager\&.Copy\&.ViewPersentageToConsole (double persentage, ref bool cancelFlag)"

.PP
Получение процентов и завершение процесса копирования 
.PP
\fBParameters\fP
.RS 4
\fIpersentage\fP Процент выполнения
.br
\fIcancelFlag\fP Закрытие потоков
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
