.TH "FileManager.CustomFileCopy" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.CustomFileCopy \- Класс для копирования файла с возможностью отслеживания промежуточных сосотояний и завершения процесса через события  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomFileCopy\fP (string Source, string Dest)"
.br
.RI "Конструктор класса "
.ti -1c
.RI "void \fBCopy\fP ()"
.br
.RI "Копирование файла "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBSourceFilePath\fP\fC [get, set]\fP"
.br
.RI "Путь к файлу для копирования "
.ti -1c
.RI "string \fBDestFilePath\fP\fC [get, set]\fP"
.br
.RI "Путь назначения "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "\fBProgressChangeDelegate\fP \fBOnProgressChanged\fP"
.br
.RI "Промежуточное событие "
.ti -1c
.RI "\fBCompletedelegate\fP \fBOnComplete\fP"
.br
.RI "Событие, генерирующееся при завершении процесса копирования "
.in -1c
.SH "Detailed Description"
.PP 
Класс для копирования файла с возможностью отслеживания промежуточных сосотояний и завершения процесса через события 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FileManager\&.CustomFileCopy\&.CustomFileCopy (string Source, string Dest)"

.PP
Конструктор класса 
.PP
\fBParameters\fP
.RS 4
\fISource\fP Текущий путь к расположению файла
.br
\fIDest\fP Путь к директории назначения
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void FileManager\&.CustomFileCopy\&.Copy ()"

.PP
Копирование файла 
.SH "Property Documentation"
.PP 
.SS "string FileManager\&.CustomFileCopy\&.DestFilePath\fC [get]\fP, \fC [set]\fP"

.PP
Путь назначения 
.SS "string FileManager\&.CustomFileCopy\&.SourceFilePath\fC [get]\fP, \fC [set]\fP"

.PP
Путь к файлу для копирования 
.SH "Event Documentation"
.PP 
.SS "\fBCompletedelegate\fP FileManager\&.CustomFileCopy\&.OnComplete"

.PP
Событие, генерирующееся при завершении процесса копирования 
.SS "\fBProgressChangeDelegate\fP FileManager\&.CustomFileCopy\&.OnProgressChanged"

.PP
Промежуточное событие 

.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
