.TH "FileManager.KeyEnter" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.KeyEnter \- Класс для осуществления действий, при нажатии на клавишу Enter  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileManager\&.ICommand< ConsoleKeyInfo >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCanExecute\fP (ConsoleKeyInfo click)"
.br
.RI "Проверка условия для выполнения метода Execute "
.ti -1c
.RI "bool \fBExecute\fP ()"
.br
.RI "Проверка, находится курсор на директории или на файле "
.in -1c
.SH "Detailed Description"
.PP 
Класс для осуществления действий, при нажатии на клавишу Enter 


.SH "Member Function Documentation"
.PP 
.SS "bool FileManager\&.KeyEnter\&.CanExecute (ConsoleKeyInfo click)"

.PP
Проверка условия для выполнения метода Execute 
.PP
\fBParameters\fP
.RS 4
\fIclick\fP Информация о нажатой клавише
.RE
.PP
\fBReturns\fP
.RS 4
true or false
.RE
.PP

.SS "bool FileManager\&.KeyEnter\&.Execute ()"

.PP
Проверка, находится курсор на директории или на файле 
.PP
\fBReturns\fP
.RS 4
Выход из приложения
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
