.TH "FileManager.CL_Copy" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.CL_Copy \- Класс для копирования файла и директории  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileManager\&.ICommand< string >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCanExecute\fP (string value)"
.br
.RI "Сравнение входящей строки с контрольной строкой "
.ti -1c
.RI "bool \fBExecute\fP ()"
.br
.RI "Копирование обьекта при помощи класса \fBCopy\fP\&. "
.ti -1c
.RI "void \fBUpdateDesktop\fP (string current, string target)"
.br
.RI "Обновление файловых панелей "
.ti -1c
.RI "\fBAttributes\fP \fBSetObjectAttributes\fP ()"
.br
.RI "Создание аттрибутов для обьекта копирования\&. "
.in -1c
.SH "Detailed Description"
.PP 
Класс для копирования файла и директории 


.SH "Member Function Documentation"
.PP 
.SS "bool FileManager\&.CL_Copy\&.CanExecute (string value)"

.PP
Сравнение входящей строки с контрольной строкой 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Входящая строка
.RE
.PP
\fBReturns\fP
.RS 4
true or false
.RE
.PP

.SS "bool FileManager\&.CL_Copy\&.Execute ()"

.PP
Копирование обьекта при помощи класса \fBCopy\fP\&. 
.SS "\fBAttributes\fP FileManager\&.CL_Copy\&.SetObjectAttributes ()"

.PP
Создание аттрибутов для обьекта копирования\&. 
.PP
\fBReturns\fP
.RS 4
Аттрибуты копируемого обьекта
.RE
.PP

.SS "void FileManager\&.CL_Copy\&.UpdateDesktop (string current, string target)"

.PP
Обновление файловых панелей 
.PP
\fBParameters\fP
.RS 4
\fIcurrent\fP Путь текущего расположения обьекта
.br
\fItarget\fP Путь назначения
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
