.TH "FileManager.Delete" 3 "Mon Mar 1 2021" "Console File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileManager.Delete \- Класс для удаления файлов или директорий  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileManager\&.ICommand< ConsoleKeyInfo >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDelete\fP (\fBFilesPanel\fP filesPanel)"
.br
.RI "Конструктор класса "
.ti -1c
.RI "\fBDelete\fP ()"
.br
.RI "Конструктор класса "
.ti -1c
.RI "bool \fBCanExecute\fP (ConsoleKeyInfo click)"
.br
.RI "Проверка условия для выполнения метода Execute "
.ti -1c
.RI "bool \fBExecute\fP ()"
.br
.RI "Запуск цепочки удаления и обновление окна программы после удаления "
.ti -1c
.RI "void \fBCheckBufferSelected\fP ()"
.br
.RI "Проверяется наличие выделенных обьектов и если такие есть, то они поочередно отправляются на удаление\&. Если выделенных обьектов нет, то отправляется на проверку обьект, на котором находится курсор\&. "
.ti -1c
.RI "void \fBCheck\fP ()"
.br
.RI "Валидация обьекта на котором находится курсор "
.ti -1c
.RI "void \fBDeleteObjectFromToList\fP ()"
.br
.RI "Создание списка обьектов для удаления и поочередная отправка их на удаление "
.ti -1c
.RI "void \fBDeleteFileOrDirectory\fP (\fBAttributes\fP attributes)"
.br
.RI "Удаление файла или директории "
.ti -1c
.RI "bool \fBConfirmation\fP (string path)"
.br
.RI "Подтверждение удаления от пользователя "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBFilesPanel\fP \fBActivePanel\fP\fC [get, set]\fP"
.br
.RI "Активная панель "
.in -1c
.SH "Detailed Description"
.PP 
Класс для удаления файлов или директорий 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FileManager\&.Delete\&.Delete (\fBFilesPanel\fP filesPanel)"

.PP
Конструктор класса 
.PP
\fBParameters\fP
.RS 4
\fIfilesPanel\fP 
.RE
.PP

.SS "FileManager\&.Delete\&.Delete ()"

.PP
Конструктор класса 
.SH "Member Function Documentation"
.PP 
.SS "bool FileManager\&.Delete\&.CanExecute (ConsoleKeyInfo click)"

.PP
Проверка условия для выполнения метода Execute 
.PP
\fBParameters\fP
.RS 4
\fIclick\fP Информация о нажатой клавише
.RE
.PP
\fBReturns\fP
.RS 4
true or false
.RE
.PP

.SS "void FileManager\&.Delete\&.Check ()"

.PP
Валидация обьекта на котором находится курсор 
.SS "void FileManager\&.Delete\&.CheckBufferSelected ()"

.PP
Проверяется наличие выделенных обьектов и если такие есть, то они поочередно отправляются на удаление\&. Если выделенных обьектов нет, то отправляется на проверку обьект, на котором находится курсор\&. 
.SS "bool FileManager\&.Delete\&.Confirmation (string path)"

.PP
Подтверждение удаления от пользователя 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP Полное имя файла или директории
.RE
.PP
\fBReturns\fP
.RS 4
true or false
.RE
.PP

.SS "void FileManager\&.Delete\&.DeleteFileOrDirectory (\fBAttributes\fP attributes)"

.PP
Удаление файла или директории 
.PP
\fBParameters\fP
.RS 4
\fIattributes\fP 
.RE
.PP

.SS "void FileManager\&.Delete\&.DeleteObjectFromToList ()"

.PP
Создание списка обьектов для удаления и поочередная отправка их на удаление 
.SS "bool FileManager\&.Delete\&.Execute ()"

.PP
Запуск цепочки удаления и обновление окна программы после удаления 
.PP
\fBReturns\fP
.RS 4
Выход из программы
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "\fBFilesPanel\fP FileManager\&.Delete\&.ActivePanel\fC [get]\fP, \fC [set]\fP"

.PP
Активная панель 

.SH "Author"
.PP 
Generated automatically by Doxygen for Console File Manager from the source code\&.
